[package]
name = "orbitkv-mooncake-sys"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
links = "orbitkv_mooncake"
build = "build.rs"

[lints]
workspace = true

[features]
default = ["cuda"]
cuda = []

[dependencies]
libc.workspace = true
libloading.workspace = true
