[workspace]
members = [
    "crates/loom-infer-cuda",
    "crates/loom-infer-validation",
    "crates/loom-infer",
]
default-members = [
    "crates/loom-infer",
    "crates/loom-infer-cuda",
]
resolver = "2"

[workspace.package]
version = "1.0.0-alpha.1"
edition = "2024"
license = "MIT"
repository = "https://github.com/feichai0017/loom-infer"
homepage = "https://feichai0017.github.io/loom-infer/"

[workspace.dependencies]
half = "2.7"
thiserror = "2.0"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"
unused_must_use = "deny"

[workspace.lints.clippy]
dbg_macro = "deny"
todo = "deny"
undocumented_unsafe_blocks = "deny"
