[package]
name = "orbitkv-metaserver"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
default-run = "orbitkv-metaserver"

[lints]
workspace = true

[lib]
name = "orbitkv_metaserver"
path = "src/lib.rs"

[[bin]]
name = "orbitkv-metaserver"
path = "src/main.rs"

[dependencies]
orbitkv-common.workspace = true
orbitkv-state.workspace = true
orbitkv-proto = { path = "../orbitkv-proto" }
tonic.workspace = true
tokio.workspace = true
clap.workspace = true
log.workspace = true
dashmap.workspace = true
uuid.workspace = true
opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
opentelemetry-prometheus.workspace = true
prometheus.workspace = true
axum.workspace = true
serde.workspace = true

[dev-dependencies]
criterion.workspace = true
tower = "0.5"

[[bench]]
name = "unregister_node"
harness = false
