[package]
name = "orbitkv-proto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[package.metadata.cargo-machete]
ignored = ["prost", "tonic-prost"]

[dependencies]
orbitkv-state.workspace = true
prost.workspace = true
tonic.workspace = true
tonic-prost.workspace = true

[build-dependencies]
tonic-prost-build = "0.14"
