[package]
name = "orbitkv-catalog"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
name = "orbitkv_catalog"
path = "src/lib.rs"

[dependencies]
libc.workspace = true
serde.workspace = true
orbitkv-state.workspace = true
parking_lot.workspace = true
uuid.workspace = true
