"""PyTorch facade for Loom's Rust-owned CUDA operator path."""

from __future__ import annotations

from .ops.activation import (
    silu_and_mul,
    silu_and_mul_dynamic_fp8,
    silu_and_mul_dynamic_fp8_out,
    silu_and_mul_dynamic_int8,
    silu_and_mul_dynamic_int8_out,
    silu_and_mul_out,
    supports_silu_and_mul,
    supports_silu_and_mul_dynamic_fp8,
    supports_silu_and_mul_dynamic_int8,
)
from .ops.attention import (
    PAGED_DECODE_MAX_CONTEXT,
    paged_decode_attention,
    paged_decode_attention_out,
    supports_paged_decode_attention,
)
from .ops.logits import (
    logits_preprocess_,
    min_p_filter_,
    supports_logits_preprocess,
    supports_min_p_filter,
)
from .ops.norm import (
    add_rms_norm_,
    rms_norm,
    rms_norm_dynamic_fp8,
    rms_norm_dynamic_fp8_out,
    rms_norm_dynamic_int8,
    rms_norm_dynamic_int8_out,
    rms_norm_out,
    supports_add_rms_norm,
    supports_rms_norm,
    supports_rms_norm_dynamic_fp8,
    supports_rms_norm_dynamic_int8,
)
from .ops.moe import (
    moe_combine,
    moe_permute,
    supports_moe_combine,
    supports_moe_permute,
)
from .ops.rope_kv import (
    rope_paged_kv_write_,
    supports_rope_paged_kv_write,
)
from .ops.sampling import (
    apply_token_penalties_,
    categorical_sample,
    greedy_sample_logprobs,
    selected_token_logprobs,
    top_k_filter_,
    top_p_renorm_,
    topk_sampled_logprobs,
    supports_apply_token_penalties,
    supports_categorical_sample,
    supports_greedy_sample_logprobs,
    supports_selected_token_logprobs,
    supports_top_k_filter,
    supports_top_p_renorm,
    supports_topk_sampled_logprobs,
    token_penalties_workspace_capacity,
)
from .ops.speculative import (
    greedy_speculative_verify,
    supports_greedy_speculative_verify,
)
from .ops.telemetry import (
    Operator,
    bridge_abi_version,
    launch_count,
    reset_launch_count,
)


__all__ = [
    "Operator",
    "PAGED_DECODE_MAX_CONTEXT",
    "add_rms_norm_",
    "apply_token_penalties_",
    "bridge_abi_version",
    "categorical_sample",
    "greedy_sample_logprobs",
    "greedy_speculative_verify",
    "launch_count",
    "logits_preprocess_",
    "min_p_filter_",
    "moe_combine",
    "moe_permute",
    "paged_decode_attention",
    "paged_decode_attention_out",
    "reset_launch_count",
    "rms_norm",
    "rms_norm_dynamic_fp8",
    "rms_norm_dynamic_fp8_out",
    "rms_norm_dynamic_int8",
    "rms_norm_dynamic_int8_out",
    "rms_norm_out",
    "rope_paged_kv_write_",
    "selected_token_logprobs",
    "silu_and_mul",
    "silu_and_mul_dynamic_fp8",
    "silu_and_mul_dynamic_fp8_out",
    "silu_and_mul_dynamic_int8",
    "silu_and_mul_dynamic_int8_out",
    "silu_and_mul_out",
    "supports_add_rms_norm",
    "supports_apply_token_penalties",
    "supports_categorical_sample",
    "supports_greedy_sample_logprobs",
    "supports_greedy_speculative_verify",
    "supports_logits_preprocess",
    "supports_min_p_filter",
    "supports_moe_combine",
    "supports_moe_permute",
    "supports_paged_decode_attention",
    "supports_rms_norm",
    "supports_rms_norm_dynamic_fp8",
    "supports_rms_norm_dynamic_int8",
    "supports_rope_paged_kv_write",
    "supports_selected_token_logprobs",
    "supports_top_k_filter",
    "supports_top_p_renorm",
    "supports_silu_and_mul",
    "supports_silu_and_mul_dynamic_fp8",
    "supports_silu_and_mul_dynamic_int8",
    "supports_topk_sampled_logprobs",
    "token_penalties_workspace_capacity",
    "top_k_filter_",
    "top_p_renorm_",
    "topk_sampled_logprobs",
]
